/*
-- Query: SELECT * FROM project.product
LIMIT 0, 1000

-- Date: 2021-09-02 16:12
*/
INSERT INTO `product` (`idPro`,`proName`,`proDescript`,`proPrice`,`proAmount`,`proMFD`,`proPathImg`,`idBrand`) VALUES (1,'MONOGRAM OMBRE SILK PAJAMA TOP','The House’s iconic Monogram motif is playfully scaled-up and printed in a summery ombre effect to give this short-sleeved pajama top a fresh lounge feel. Cut from comfortable, lightweight silk that further relaxes the boxy silhouette. White piping and a front patch pocket refine the easy-to-wear style.',73999.00,100,'2021-02-23','img01.png',1);
INSERT INTO `product` (`idPro`,`proName`,`proDescript`,`proPrice`,`proAmount`,`proMFD`,`proPathImg`,`idBrand`) VALUES (2,'GALAXY PRINT MIXED-MATERIAL T-SHIRT','The playful graphic on this mixed-material T-shirt is inspired by comic books: vibrant LV Initials and Monogram Flowers collide with stars and planets on printed silk twill. The contrasting back is cut slightly longer, in cotton jersey. The silhouette is relaxed and roomy. The top square button on the shoulder is engraved with a House signature.',3039900.00,50,'2020-03-30','img03.png',1);
INSERT INTO `product` (`idPro`,`proName`,`proDescript`,`proPrice`,`proAmount`,`proMFD`,`proPathImg`,`idBrand`) VALUES (3,'MIXED KNIT LIGHTWEIGHT SUMMER PULLOVER','Different textures and tones of natural fibers combine to create this summer pullover. The shoulders and left sleeve stand out in contrast cotton poplin, while a mix of knitted cotton panels complete the silhouette. The collection’s essential leather Monogram patch signs the chest.',80880.00,80,'2019-06-15','img05.png',1);
INSERT INTO `product` (`idPro`,`proName`,`proDescript`,`proPrice`,`proAmount`,`proMFD`,`proPathImg`,`idBrand`) VALUES (4,'SHEIN Slogan Graphic Hoodie','Wide top in sweatshirt fabric with a lined, drawstring hood, long raglan sleeves and ribbing at the cuffs and hem. Soft brushed inside.',380.00,65,'2020-12-23','img07.png',2);
INSERT INTO `product` (`idPro`,`proName`,`proDescript`,`proPrice`,`proAmount`,`proMFD`,`proPathImg`,`idBrand`) VALUES (5,'SHEIN Twist Hem Rib-knit Tee','Short twist in a soft, fine knit with a lightly brushed finish. Round neckline and long sleeves.',160.00,110,'2019-11-06','img09.png',2);
INSERT INTO `product` (`idPro`,`proName`,`proDescript`,`proPrice`,`proAmount`,`proMFD`,`proPathImg`,`idBrand`) VALUES (6,'SHEIN Ribbed Mock Neck Lettuce-Edge Top','Short Lettuce Trim in soft cotton jersey with overlocked edges.',180.00,60,'2021-08-09','img11.png',2);
INSERT INTO `product` (`idPro`,`proName`,`proDescript`,`proPrice`,`proAmount`,`proMFD`,`proPathImg`,`idBrand`) VALUES (7,'Cut-out-detail Top','Short-sleeved top in soft cotton jersey with a small stand-up collar and cut-out shape at the top. Overlocked edges around the collar, cuffs and hem.',399.00,55,'2019-01-09','img16.png',3);
INSERT INTO `product` (`idPro`,`proName`,`proDescript`,`proPrice`,`proAmount`,`proMFD`,`proPathImg`,`idBrand`) VALUES (8,'Motif-detail Hoodie','Hoodie in soft sweatshirt fabric with a motif. Lined, drawstring hood, low dropped shoulders, long sleeves and ribbing at the cuffs and hem. Soft brushed inside. The polyester content of the hoodie is recycled.',499.00,100,'2020-04-06','img18.png',3);
INSERT INTO `product` (`idPro`,`proName`,`proDescript`,`proPrice`,`proAmount`,`proMFD`,`proPathImg`,`idBrand`) VALUES (9,'Jersey Dress','Short jersey dress with a small gathered collar and an opening and button at the back of the neck. Seam at the waist and long, cuffed sleeves. Unlined.',799.00,55,'2021-07-28','img21.png',3);
INSERT INTO `product` (`idPro`,`proName`,`proDescript`,`proPrice`,`proAmount`,`proMFD`,`proPathImg`,`idBrand`) VALUES (10,'WOMEN premium lambswool crew neck Long Sleevesweater','Fabric Details 100% and wool. Washing instruction that use Hand wash cold.',990.00,150,'2021-05-21','img23.png',4);
INSERT INTO `product` (`idPro`,`proName`,`proDescript`,`proPrice`,`proAmount`,`proMFD`,`proPathImg`,`idBrand`) VALUES (11,'WOMEN Rayon Long Sleeve Blouse','Soft, silky rayon fabric and Wrinkle-resistant even after washing for easy care.',790.00,85,'2021-02-18','img27.png',4);
INSERT INTO `product` (`idPro`,`proName`,`proDescript`,`proPrice`,`proAmount`,`proMFD`,`proPathImg`,`idBrand`) VALUES (12,'WOMEN color crew neck Short Sleeve T-Shirt','Made from soft and supple cotton viscose. A crew neck with a perfect opening at the neck.',190.00,68,'2019-10-03','img30.png',4);