--1. List all PRODUCTNAME that PRODUCTCODE is the same from PRODUCTS and ORDERDETAILS 
SELECT PRODUCTNAME FROM PRODUCTS P, ORDERDETAILS O WHERE P.PRODUCTCODE = O.PRODUCTCODE;
 
--2. List all PAYMENTDATE and CUSTOMERNAME who have CUSTOMERNUMBER for PAYMENTS 
SELECT PAYMENTDATE, CUSTOMERNAME FROM CUSTOMERS C, PAYMENTS P WHERE P.CUSTOMERNUMBER = C.CUSTOMERNUMBER; 

--3. List all CUSTOMERNAME who are in ‘USA’ and list all FIRSTNAME of EMPLOYEES who sales(EMPLOYEENUMBER)for CUSTOMERS in ‘USA’ 
SELECT CUSTOMERNAME,FIRSTNAME FROM CUSTOMERS C,EMPLOYEES E WHERE C.COUNTRY = 'USA' AND C.SALESREPEMPLOYEENUMBER = E.EMPLOYEENUMBER;
 
--4. List all ORDERNUMBER and STATUS of PRODUCTNAME = 'The Queen Mary' or PRODUCTNAME = 'HMS Bounty' or 'The Mayflower'
SELECT ORDERNUMBER, STATUS FROM ORDERS, PRODUCTS P WHERE P.PRODUCTNAME IN ('The Queen Mary', 'HMS Bounty', 'The Mayflower');

--5. List all ORDERNUMBER and STATUS of PRODUCTNAME = ' 1940s Ford truck'
SELECT ORDERNUMBER, STATUS FROM ORDERS, PRODUCTS P WHERE P.PRODUCTNAME = ' 1940s Ford truck';

